[project]
name = "exifdoctor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "pyside6>=6.9.0",
    "rich>=14.0.0",
]
